# Generated by Django 4.0.10 on 2025-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0026_vrarexperiment_multilingualquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='llm_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='llm_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='llm_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
