# Generated by Django 4.0.10 on 2025-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0031_activity_short_llm_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activityproposal',
            name='category_in_risk',
        ),
        migrations.AddField(
            model_name='activityproposal',
            name='categories_in_risk',
            field=models.ManyToManyField(related_name='proposals', to='authoringtool.categorytag'),
        ),
    ]
