# Generated by Django 4.0.10 on 2025-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0033_remove_activityproposal_flag_activityproposal_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='QValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('Dynamic correctness threshold', 'Dynamic correctness threshold'), ('Extreme correctness pattern', 'Extreme correctness pattern'), ('Engagement risk (too slow, question)', 'Engagement risk (too slow, question)'), ('Engagement risk (too fast, question)', 'Engagement risk (too fast, question)'), ('Engagement risk (too slow, non-question)', 'Engagement risk (too slow, non-question)'), ('Engagement risk (too fast, non-question)', 'Engagement risk (too fast, non-question)'), ('Timing discrepancy under extreme correctness', 'Timing discrepancy under extreme correctness')], max_length=128)),
                ('category', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=16)),
                ('action', models.CharField(choices=[('create', 'Create'), ('revise', 'Revise'), ('skip', 'Skip')], max_length=16)),
                ('q_value', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('flag_type', 'category', 'action')},
            },
        ),
    ]
