# Generated by Django 4.0.10 on 2025-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0034_qvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='qvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
