# Generated by Django 4.0.10 on 2025-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0035_qvalue_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproposal',
            name='json_action',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
