# Generated by Django 4.0.10 on 2025-06-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0037_userproposalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='True if created by user from proposals'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='origin_scenario',
            field=models.ForeignKey(blank=True, help_text='Original scenario this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_clones', to='authoringtool.scenario'),
        ),
    ]
