# Generated by Django 4.0.10 on 2024-04-27 18:14

from django.db import migrations, models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0014_userscenarioscore_useranswer'),
    ]

    operations = [
        # UserAnswer is already created in 0014, this migration just needs to ensure the schema is correct
        migrations.AlterField(
            model_name='useranswer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
