# Generated by Django 4.0.10 on 2024-04-27 18:37

from django.db import migrations, models


def convert_timing_with_sql(apps, schema_editor):
    """
    Convert timing column from interval type to integer type.
    We need to do this in steps:
    1. Create a new integer column
    2. Copy/convert data
    3. Drop old column
    4. Rename new column
    """
    db_alias = schema_editor.connection.alias
    schema_editor.execute(
        'ALTER TABLE "authoringtool_useranswer" '
        'ADD COLUMN "timing_int" integer DEFAULT 0'
    )
    # Convert interval to integer (seconds)
    schema_editor.execute(
        'UPDATE "authoringtool_useranswer" '
        'SET "timing_int" = EXTRACT(EPOCH FROM "timing")::integer '
        'WHERE "timing" IS NOT NULL'
    )
    # Drop old column and rename new one
    schema_editor.execute(
        'ALTER TABLE "authoringtool_useranswer" '
        'DROP COLUMN "timing"'
    )
    schema_editor.execute(
        'ALTER TABLE "authoringtool_useranswer" '
        'RENAME COLUMN "timing_int" TO "timing"'
    )


def reverse_timing(apps, schema_editor):
    """Reverse is not easily possible, so we'll do nothing."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0015_alter_useranswer_created_on'),
    ]

    operations = [
        migrations.RunPython(convert_timing_with_sql, reverse_timing),
        migrations.AlterField(
            model_name='useranswer',
            name='timing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
