# Generated by Django 4.0.10 on 2024-04-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0016_alter_useranswer_timing'),
    ]

    operations = [
        # This migration originally tried to re-create UserAnswer, which already exists.
        # Removed empty CreateModel operation to avoid duplicate table error.
    ]
