# Generated by Django 4.0.10 on 2025-06-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0027_activity_llm_context_phase_llm_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=16)),
                ('flag_type', models.CharField(max_length=128)),
                ('flag_reason', models.TextField()),
                ('is_at_risk', models.BooleanField(default=True)),
                ('value_at_risk', models.FloatField(blank=True, null=True)),
                ('threshold_used', models.FloatField(blank=True, null=True)),
                ('auto_flagged', models.BooleanField(default=True)),
                ('flagged_on', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='authoringtool.activity')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoringtool.phase')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoringtool.scenario')),
            ],
            options={
                'verbose_name': 'Activity Flag',
                'verbose_name_plural': 'Activity Flags',
            },
        ),
        migrations.AddIndex(
            model_name='activityflag',
            index=models.Index(fields=['activity', 'category'], name='authoringto_activit_1e6bee_idx'),
        ),
    ]
