# Generated by Django 4.0.10 on 2025-06-07 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0028_activityflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_act_llm_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_in_risk', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=16)),
                ('proposal_type', models.CharField(choices=[('create', 'Create New Activity'), ('revise', 'Revise Activity'), ('skip', 'Skip Activity')], max_length=32)),
                ('suggested_action', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='authoringtool.activity')),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='authoringtool.activityflag')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='authoringtool.phase')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Teacher who accepted/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='authoringtool.scenario')),
            ],
            options={
                'verbose_name': 'Activity Proposal',
                'verbose_name_plural': 'Activity Proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
