# Generated by Django 4.0.10 on 2025-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0029_activity_related_act_llm_context_activityproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='llm_image_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
