# Generated by Django 4.0.10 on 2025-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0030_activity_llm_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short_llm_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
