# Generated by Django 4.0.10 on 2025-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0032_categorytag_remove_activityproposal_category_in_risk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityproposal',
            name='flag',
        ),
        migrations.AddField(
            model_name='activityproposal',
            name='flag',
            field=models.ManyToManyField(blank=True, null=True, related_name='proposals', to='authoringtool.activityflag'),
        ),
    ]
