# Generated by Django 4.0.10 on 2025-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0038_scenario_is_personal_scenario_origin_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproposal',
            name='translated_action',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
