# Generated by Django 4.0.10 on 2025-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0039_activityproposal_translated_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproposalreview',
            name='teacher_edited_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
