# Generated by Django 4.0.10 on 2025-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0040_userproposalreview_teacher_edited_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproposal',
            name='json_translated_action',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
