# Generated by Django 5.2.16 on 2026-07-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0055_userproposalreview_rejection_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproposalreview',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproposalreview',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='ai_metrics_min_implementations',
            field=models.PositiveIntegerField(default=200, help_text='Minimum number of student implementations required before Metrics & AI / Proposals are shown without a warning.'),
        ),
        migrations.CreateModel(
            name='ActivityProposalEditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_number', models.PositiveIntegerField()),
                ('edited_json', models.JSONField()),
                ('changed_fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_events', to='authoringtool.userproposalreview')),
            ],
            options={
                'verbose_name': 'Activity Proposal Edit Event',
                'verbose_name_plural': 'Activity Proposal Edit Events',
                'ordering': ['review', 'edit_number'],
                'constraints': [models.UniqueConstraint(fields=('review', 'edit_number'), name='unique_review_edit_number')],
            },
        ),
    ]
