# Generated by Django 5.2.16 on 2026-07-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0056_userproposalreview_edit_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_proposal_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_generation_runs', to='authoringtool.scenario')),
            ],
            options={
                'verbose_name': 'Proposal Generation Run',
                'verbose_name_plural': 'Proposal Generation Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityproposal',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='authoringtool.proposalgenerationrun'),
        ),
        migrations.AddConstraint(
            model_name='proposalgenerationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('scenario',), name='unique_current_run_per_scenario'),
        ),
    ]
