# Generated by Django 5.2.16 on 2026-07-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_exact_structure_candidates(apps, schema_editor):
    """Surface only strong legacy matches; never link families automatically."""
    ScenarioVersion = apps.get_model('authoringtool', 'ScenarioVersion')
    Candidate = apps.get_model('authoringtool', 'ScenarioFamilyCandidate')

    grouped = {}
    versions = (
        ScenarioVersion.objects
        .filter(
            is_current=True,
            scenario__current_version_id=models.F('id'),
            scenario__family__isnull=False,
        )
        .select_related('scenario')
        .order_by('scenario_id')
    )
    for version in versions.iterator():
        grouped.setdefault(version.structure_fingerprint, []).append(version)

    for fingerprint, matching_versions in grouped.items():
        for left_index, left_version in enumerate(matching_versions):
            for right_version in matching_versions[left_index + 1:]:
                left = left_version.scenario
                right = right_version.scenario
                if left.family_id == right.family_id:
                    continue
                if left.id > right.id:
                    left, right = right, left
                    left_version, right_version = right_version, left_version
                different_languages = (
                    bool((left.language or '').strip())
                    and bool((right.language or '').strip())
                    and (left.language or '').strip().casefold()
                    != (right.language or '').strip().casefold()
                )
                Candidate.objects.get_or_create(
                    scenario_a_id=left.id,
                    scenario_b_id=right.id,
                    scenario_a_version_id=left_version.id,
                    scenario_b_version_id=right_version.id,
                    defaults={
                        'similarity_score': 0.88,
                        'family_score': 0.88,
                        'topic_score': 0,
                        'component_scores': {
                            'structure': 1.0,
                            'semantic': 0.0,
                            'embedding': 0.0,
                            'lexical': 0.0,
                            'metadata': 0.0,
                            'lineage': 0.0,
                            'origin': 0.0,
                        },
                        'reasons': [
                            (
                                'Legacy scenarios have identical immutable '
                                'structural fingerprints.'
                            )
                        ],
                        'suggested_relationship': (
                            'translation'
                            if different_languages
                            else 'adaptation'
                        ),
                        'decision': 'pending',
                        'target_family_id': left.family_id,
                        'is_current': True,
                        'detection_method': 'legacy-exact-structure-v1',
                    },
                )


def reverse_legacy_candidates(apps, schema_editor):
    Candidate = apps.get_model('authoringtool', 'ScenarioFamilyCandidate')
    Candidate.objects.filter(
        detection_method='legacy-exact-structure-v1',
        decision='pending',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0063_evidence_compatibility_pooling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioFamilyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('family_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('topic_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('component_scores', models.JSONField(default=dict)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('suggested_relationship', models.CharField(choices=[('translation', 'Same family — translation'), ('adaptation', 'Same family — adaptation'), ('related_topic', 'Related topic only')], max_length=30)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('translation', 'Same family — translation'), ('adaptation', 'Same family — adaptation'), ('related_topic', 'Related topic only'), ('unrelated', 'Not related'), ('deferred', 'Review later')], db_index=True, default='pending', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('detection_method', models.CharField(default='explainable-hybrid-v1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scenario_family_candidates', to=settings.AUTH_USER_MODEL)),
                ('scenario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_candidates_as_a', to='authoringtool.scenario')),
                ('scenario_a_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_candidates_as_a', to='authoringtool.scenarioversion')),
                ('scenario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_candidates_as_b', to='authoringtool.scenario')),
                ('scenario_b_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_candidates_as_b', to='authoringtool.scenarioversion')),
                ('target_family', models.ForeignKey(blank=True, help_text='Family that should remain when a same-family decision is approved. Leave blank to use the recommended family.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_family_candidates', to='authoringtool.scenariofamily')),
            ],
            options={
                'verbose_name': 'Scenario Family Candidate',
                'verbose_name_plural': 'Scenario Family Candidates',
                'ordering': ['decision', '-similarity_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioFamilyMatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('translation', 'Same family — translation'), ('adaptation', 'Same family — adaptation'), ('related_topic', 'Related topic only'), ('unrelated', 'Not related'), ('deferred', 'Review later')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_events', to='authoringtool.scenariofamilycandidate')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_family_match_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario Family Match Decision',
                'verbose_name_plural': 'Scenario Family Match Decisions',
                'ordering': ['-decided_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSimilarityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_digest', models.CharField(db_index=True, max_length=64)),
                ('feature_schema', models.PositiveSmallIntegerField(default=1)),
                ('features', models.JSONField(default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=255)),
                ('embedding_error', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_profile', to='authoringtool.scenario')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_profiles', to='authoringtool.scenarioversion')),
            ],
            options={
                'verbose_name': 'Scenario Similarity Profile',
                'verbose_name_plural': 'Scenario Similarity Profiles',
                'ordering': ['scenario__name', 'scenario_id'],
            },
        ),
        migrations.AddIndex(
            model_name='scenariofamilycandidate',
            index=models.Index(fields=['is_current', 'decision', '-similarity_score'], name='scenario_match_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenariofamilycandidate',
            constraint=models.CheckConstraint(check=models.Q(('scenario_a__lt', models.F('scenario_b'))), name='scenario_candidate_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='scenariofamilycandidate',
            constraint=models.UniqueConstraint(fields=('scenario_a', 'scenario_b', 'scenario_a_version', 'scenario_b_version'), name='unique_scenario_candidate_version_pair'),
        ),
        migrations.AddConstraint(
            model_name='scenariofamilycandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('scenario_a', 'scenario_b'), name='unique_current_scenario_candidate_pair'),
        ),
        migrations.RunPython(
            backfill_exact_structure_candidates,
            reverse_legacy_candidates,
        ),
    ]
