# Generated by Django 5.2.16 on 2026-07-28 07:30

import hashlib
import json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_revision_status_and_legacy_boundaries(apps, schema_editor):
    Scenario = apps.get_model('authoringtool', 'Scenario')
    ScenarioImplementation = apps.get_model(
        'authoringtool',
        'ScenarioImplementation',
    )
    ScenarioVersion = apps.get_model('authoringtool', 'ScenarioVersion')
    UserAnswer = apps.get_model('authoringtool', 'UserAnswer')
    UserScenarioScore = apps.get_model(
        'authoringtool',
        'UserScenarioScore',
    )

    ScenarioVersion.objects.all().update(
        revision_status='published',
        published_by_id=models.F('created_by_id'),
        published_at=models.F('created_at'),
    )

    legacy_scenario_ids = set(
        ScenarioImplementation.objects.filter(
            version_confidence='legacy_unknown',
        ).values_list('scenario_id', flat=True)
    )
    legacy_scenario_ids.update(
        UserScenarioScore.objects.filter(
            version_confidence='legacy_unknown',
        ).values_list('scenario_id', flat=True)
    )
    legacy_scenario_ids.update(
        UserAnswer.objects.filter(
            version_confidence='legacy_unknown',
        ).values_list('activity__scenario_id', flat=True)
    )

    for scenario in Scenario.objects.filter(
        id__in=legacy_scenario_ids,
    ).iterator():
        if ScenarioVersion.objects.filter(
            scenario_id=scenario.id,
            version_number=0,
        ).exists():
            continue
        marker = {
            'schema': 1,
            'legacy_unknown': True,
            'scenario_id': scenario.id,
        }
        digest = hashlib.sha256(
            json.dumps(
                marker,
                sort_keys=True,
                separators=(',', ':'),
            ).encode('utf-8')
        ).hexdigest()
        ScenarioVersion.objects.create(
            scenario_id=scenario.id,
            version_number=0,
            structure_fingerprint=digest,
            content_fingerprint=digest,
            snapshot={
                **marker,
                'structure': {
                    'schema': 1,
                    'legacy_unknown': True,
                    'phases': [],
                },
                'content': {
                    'schema': 1,
                    'legacy_unknown': True,
                    'phases': [],
                },
            },
            change_summary=(
                'Legacy evidence boundary; exact historical structure is '
                'unknown'
            ),
            is_current=False,
            revision_status='legacy',
        )


class Migration(migrations.Migration):
    # Commit version-status backfill before Django emits deferred PostgreSQL
    # indexes for the newly added publisher foreign key.
    atomic = False

    dependencies = [
        ('authoringtool', '0065_activity_implementation_lineage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scenario_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='revision_status',
            field=models.CharField(choices=[('legacy', 'Legacy revision'), ('published', 'Published revision')], default='published', max_length=20),
        ),
        migrations.CreateModel(
            name='ScenarioRevisionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('structure_fingerprint', models.CharField(blank=True, max_length=64)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_drafts', to='authoringtool.scenarioversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_revision_drafts', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_draft', to='authoringtool.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Revision Draft',
                'verbose_name_plural': 'Scenario Revision Drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(
            backfill_revision_status_and_legacy_boundaries,
            migrations.RunPython.noop,
            atomic=True,
        ),
    ]
