# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0066_revision_publish_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_confidence',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_status',
            field=models.CharField(
                choices=[
                    ('not_requested', 'Not requested'),
                    ('pending', 'Queued or running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                db_index=True,
                default='not_requested',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='scenariofamilycandidate',
            name='llm_suggested_relationship',
            field=models.CharField(
                blank=True,
                choices=[
                    ('translation', 'Same family — translation'),
                    ('adaptation', 'Same family — adaptation'),
                    ('related_topic', 'Related topic only'),
                    ('unrelated', 'Not related'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='ScenarioFamilyReviewProxy',
            fields=[],
            options={
                'verbose_name': 'Scenario family review dashboard',
                'verbose_name_plural': 'Scenario family review dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authoringtool.scenariofamily',),
        ),
    ]
