# Generated by Django 5.2.16 on 2026-10-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0068_scenario_use_family_evidence_pooling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('exact_match', models.BooleanField(default=False, help_text='Every reachable activity and route matches 1:1.')),
                ('structure_score', models.FloatField(default=0)),
                ('route_score', models.FloatField(default=0)),
                ('anchor_score', models.FloatField(default=0, help_text='Share of numbers, formulas and images found in both.')),
                ('differences', models.JSONField(blank=True, default=list)),
                ('activity_map', models.JSONField(blank=True, default=list, help_text='Matched [scenario A activity id, scenario B activity id].')),
                ('flow_signature_a', models.CharField(blank=True, max_length=64)),
                ('flow_signature_b', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed translation'), ('rejected', 'Not a translation'), ('changed', 'Changed since review')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_translation_matches', to=settings.AUTH_USER_MODEL)),
                ('scenario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_matches_as_a', to='authoringtool.scenario')),
                ('scenario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_matches_as_b', to='authoringtool.scenario')),
            ],
            options={
                'verbose_name': 'Translation Match',
                'verbose_name_plural': 'Translation Matches',
                'ordering': ['-confidence', 'scenario_a_id', 'scenario_b_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('scenario_a__lt', models.F('scenario_b'))), name='translation_match_ordered_pair'), models.UniqueConstraint(fields=('scenario_a', 'scenario_b'), name='unique_translation_match_pair')],
            },
        ),
    ]
