from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('scenarios/', views.scenarios, name='scenarios'),
    path('scenarios/createScenario/', views.createScenario, name='createScenario'),
    path('scenarios/createScenario/createScenarioData/', views.createScenarioData, name='createScenarioData'),
    path('scenarios/updateScenario/<int:id>', views.updateScenario, name='updateScenario'),
    path('scenarios/updateScenario/updateScenarioData/<int:id>', views.updateScenarioData, name='updateScenarioData'),
    path('scenarios/deleteScenario/<int:id>', views.deleteScenario, name='deleteScenario'),
    path('scenarios/viewScenario/<int:id>', views.viewScenario, name='viewScenario'),
    path('scenarios/<int:id>/createPhase/', views.createPhase, name='createPhase'),
    path('scenarios/<int:id>/createPhaseData/', views.createPhaseData, name='createPhaseData'),
    path('scenarios/<int:scenario_id>/updatePhase/<int:phase_id>', views.updatePhase, name='updatePhase'),
    path('scenarios/<int:scenario_id>/updatePhaseData/<int:phase_id>', views.updatePhaseData, name='updatePhaseData'),
    path('scenarios/<int:scenario_id>/deletePhase/<int:phase_id>', views.deletePhase, name='deletePhase'),
    path('scenarios/<int:scenario_id>/viewPhase/<int:phase_id>', views.viewPhase, name='phase'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/createActivity/', views.createActivity, name='createActivity'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/createActivityData/', views.createActivityData, name='createActivityData'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/updateActivity/<int:activity_id>', views.updateActivity, name='updateActivity'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/updateActivityData/<int:activity_id>', views.updateActivityData, name='updateActivityData'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/deleteActivity/<int:activity_id>', views.deleteActivity, name='deleteActivity'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/createAnswer/', views.createAnswers, name='createAnswers'),
    path('scenarios/<int:scenario_id>/viewPhase/<int:phase_id>/viewActivity/<int:activity_id>/', views.viewActivity, name='activity'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/deleteAnswer/<int:answer_id>', views.deleteAnswer, name='deleteAnswer'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/updateAnswers/', views.updateAnswers, name='updateAnswers'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/criterion', views.createCriterion, name='createCriterion'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/criterionData', views.createCriterionData, name='createCriterionData'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/updateCriterion', views.updateCriterion, name='updateCriterion'),
    path('scenarios/<int:scenario_id>/phase/<int:phase_id>/activity/<int:activity_id>/updateCriterionData', views.updateCriterionData, name='updateCriterionData'),
    path('sankey_data/<int:scenario_id>/', views.sankey_data, name='sankey_data'),
    path('activity_answers_data/<int:scenario_id>/', views.activity_answers_data, name='activity_answer_data'),
    path('performance_data/<int:scenario_id>/', views.performance_data, name='performance_data'),
    path('time_spent_data/<int:scenario_id>/', views.time_spent_data, name='time_spent_data'),
    path('detailed_phase_scores_data/<int:scenario_id>/', views.detailed_phase_scores_data, name='detailed_phase_scores_data'),
    path('performers_data/<int:scenario_id>/', views.performers_data, name='performers_data'),
    path('time_spent_by_performer_type/<int:scenario_id>/', views.time_spent_by_performer_type, name='time_spent_by_performer_type'),
    path('performance_by_department/<int:scenario_id>/', views.performance_by_department, name='performance_by_department'),
    path('duplicate_scenario/<int:scenario_id>/', views.duplicate_scenario, name='duplicate_scenario'),
    path('final_performance_data/<int:scenario_id>/', views.final_performance, name='final_performance'),
    path('scenario_paths/<int:scenario_id>/', views.scenario_paths, name='scenario_paths'),
    # path('ltiintegration/', views.lms_lti_launch, name='lms_lti_launch'),
    path('ltiintegration/<int:experiment_id>/', views.lms_lti_launch, name='lti_integration_in'),
    path('lab_sessions_data/<int:scenario_id>/', views.lab_sessions_data, name='lab_sessions_data'),
    path('get_sankey_task_status/<str:task_id>/', views.get_sankey_task_status, name='get_sankey_task_status'),
    path('get_final_performance_task_status/<str:task_id>/', views.get_final_performance_task_status, name='get_final_performance_task_status'),
    path('get_performance_data_task_status/<str:task_id>/', views.get_performance_data_task_status, name='get_performance_data_task_status'),
    path('get_detailed_phase_scores_data_task_status/<str:task_id>/', views.get_detailed_phase_scores_data_task_status, name='get_detailed_phase_scores_data_task_status'),
    path('get_performers_data_task_status/<str:task_id>/', views.get_performers_data_task_status, name='get_performers_data_task_status'),
    path('get_activity_answers_data_task_status/<str:task_id>/', views.get_activity_answers_data_task_status, name='get_activity_answers_data_task_status'),
    path('get_time_spent_data_task_status/<str:task_id>/', views.get_time_spent_data_task_status, name='get_time_spent_data_task_status'),
    path('get_scenario_paths_task_status/<str:task_id>/', views.get_scenario_paths_task_status, name='get_scenario_paths_task_status'),
    path('get_time_spent_task_status/<str:task_id>/', views.get_time_spent_task_status, name='get_time_spent_task_status'),
    path('student_performance_metrics/<int:scenario_id>/', views.student_performance_metrics, name='student_performance_metrics'),
    path('get_student_performance_metrics_task_status/<str:task_id>/', views.get_student_performance_metrics_task_status, name='get_student_performance_metrics_task_status'),
    path('get_teacher_groups/<int:scenario_id>/', views.get_teacher_groups, name='get_teacher_groups'),
    # AI Metrics Page
    path('scenarios/<int:scenario_id>/aimetrics/', views.ai_metrics, name='ai_metrics'),
    # Metrics
    path('category_metrics/<int:scenario_id>/', views.category_metrics_view, name='category_metrics'),
    path('category_metrics_status/<str:task_id>/', views.category_metrics_status, name='category_metrics_status'),
    # Metric Analysis
    path('risk_flags/<int:scenario_id>/', views.risk_flags_view, name='risk_flags_view'),
    path('risk_flags_status/<str:task_id>/', views.risk_flags_status, name='risk_flags_status'),
    # LLM Generation
    path('scenarios/<int:scenario_id>/generate_llm_context/', views.trigger_llm_context_task, name='generate_llm_context'),
    path('scenarios/llm_context_status/<str:task_id>/', views.get_llm_context_task_status, name='llm_context_status'),
    # Proposals
    path('scenarios/<int:scenario_id>/proposals/', views.proposal_list_view, name='proposal_list'),
    path('scenarios/<int:scenario_id>/proposals/<int:pk>/accept/', views.accept_proposal, name='accept_proposal'),
    path('scenarios/<int:scenario_id>/proposals/<int:pk>/reject/', views.reject_proposal, name='reject_proposal'),
    path('proposals/<int:scenario_id>/create/', views.create_personal_scenario, name='create_personal_scenario'),
    # PDF on RAG
    path('scenario/<int:scenario_id>/delete_rag_pdf/<str:filename>/', views.delete_rag_pdf, name='delete_rag_pdf'),
    # Edit on Proposals
    path("proposals/<int:scenario_id>/<int:pk>/edit/", views.edit_proposal_json, name="edit_proposal_json"),
    path("rag_pdfs/scenario_<int:scenario_id>/<str:filename>", views.serve_rag_pdf, name="serve_rag_pdf"),
]
