# Generated by Django 5.2.16 on 2026-07-15 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoringtool', '0058_backfill_proposal_generation_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('assign_to_all', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to=settings.AUTH_USER_MODEL)),
                ('excluded_scenarios', models.ManyToManyField(blank=True, related_name='excluded_feedback_forms', to='authoringtool.scenario')),
                ('included_scenarios', models.ManyToManyField(blank=True, related_name='included_feedback_forms', to='authoringtool.scenario')),
            ],
            options={
                'ordering': ['-created_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('choice', 'Multiple Choice'), ('text', 'Free Text')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackform')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='authoringtool.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackresponse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedbackresponse',
            constraint=models.UniqueConstraint(fields=('form', 'user', 'scenario'), name='unique_feedback_response'),
        ),
        migrations.AddConstraint(
            model_name='feedbackanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_feedback_answer_per_question'),
        ),
    ]
